<<<<<<< HEAD
# Generated by Django 4.2.14 on 2024-07-30 23:58

=======
# Generated by Django 5.1.1 on 2025-05-29 18:22

import django.db.models.deletion
>>>>>>> e62255e (Atualizações no projeto)
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        ('empresas', '0001_initial'),
>>>>>>> e62255e (Atualizações no projeto)
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
<<<<<<< HEAD
                ('cpf_cnpj', models.CharField(max_length=18, unique=True)),
                ('endereco', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=9)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
=======
                ('cpf_cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('endereco', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresas.empresa', verbose_name='Empresa')),
>>>>>>> e62255e (Atualizações no projeto)
            ],
        ),
    ]
