<<<<<<< HEAD
# Generated by Django 5.0.7 on 2024-08-12 20:58
=======
# Generated by Django 5.1.1 on 2025-05-29 18:22
>>>>>>> e62255e (Atualizações no projeto)

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
<<<<<<< HEAD
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='empresas.empresa')),
=======
                ('empresa_padrao', models.ForeignKey(help_text='Empresa padrão', on_delete=django.db.models.deletion.PROTECT, to='empresas.empresa')),
                ('empresas_acessiveis', models.ManyToManyField(related_name='usuarios', to='empresas.empresa')),
>>>>>>> e62255e (Atualizações no projeto)
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
