# Generated by Django 5.1.1 on 2025-06-03 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioEmpresaRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('financeiro', 'Financeiro'), ('leitura', 'Somente Leitura')], default='leitura', max_length=20)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
                ('perfil_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfilusuario')),
            ],
            options={
                'verbose_name': 'Papel de Usuário por Empresa',
                'verbose_name_plural': 'Papéis de Usuários por Empresa',
                'unique_together': {('perfil_usuario', 'empresa')},
            },
        ),
    ]
