# Generated by Django 4.2.14 on 2024-07-31 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateField()),
                ('data_termino', models.DateField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='andamento', max_length=10)),
                ('tipo', models.CharField(choices=[('cliente', 'Cliente'), ('fornecedor', 'Fornecedor')], max_length=10)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='contratos/')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fornecedores.fornecedor')),
            ],
        ),
    ]
