<<<<<<< HEAD
# Generated by Django 4.2.14 on 2024-07-31 00:14

from django.db import migrations, models
import django.db.models.deletion
=======
# Generated by Django 5.1.1 on 2025-05-29 18:22

import django.db.models.deletion
from django.db import migrations, models
>>>>>>> e62255e (Atualizações no projeto)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
<<<<<<< HEAD
        ('fornecedores', '0001_initial'),
=======
        ('empresas', '0001_initial'),
        ('fornecedores', '0001_initial'),
        ('funcionarios', '0001_initial'),
        ('projetos', '0001_initial'),
>>>>>>> e62255e (Atualizações no projeto)
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('numero', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateField()),
                ('data_termino', models.DateField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='andamento', max_length=10)),
                ('tipo', models.CharField(choices=[('cliente', 'Cliente'), ('fornecedor', 'Fornecedor')], max_length=10)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='contratos/')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fornecedores.fornecedor')),
            ],
        ),
=======
                ('valor_parcela', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('periodicidade_vencimento', models.CharField(blank=True, choices=[('mensal', 'Mensal'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], max_length=10, null=True)),
                ('data_primeiro_vencimento', models.DateField(blank=True, null=True)),
                ('horizonte_projecao', models.IntegerField(blank=True, help_text='Usado apenas para contratos sem data de término', null=True, verbose_name='Horizonte de Projeção (meses)')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateField()),
                ('data_termino', models.DateField(blank=True, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='andamento', max_length=10)),
                ('tipo', models.CharField(choices=[('cliente', 'Cliente'), ('fornecedor', 'Fornecedor'), ('funcionario', 'Funcionario')], max_length=11)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='contratos/')),
                ('is_deleted', models.BooleanField(default=False)),
                ('confirmado', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresas.filial', verbose_name='Filial')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fornecedores.fornecedor')),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='funcionarios.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='ProjecaoFaturamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vencimento', models.DateField()),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pago', models.BooleanField(blank=True, default=False, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projecoes_faturamento', to='contratos.contrato')),
            ],
        ),
        migrations.CreateModel(
            name='ContratoProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_projeto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrato_projetos', to='contratos.contrato')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrato_projetos', to='projetos.projeto')),
            ],
            options={
                'unique_together': {('contrato', 'projeto')},
            },
        ),
>>>>>>> e62255e (Atualizações no projeto)
    ]
