# Generated by Django 5.1.1 on 2025-06-02 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_remove_contrato_filial_contrato_empresa'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresas.empresa', verbose_name='Empresa'),
        ),
    ]
