# Generated by Django 5.0.7 on 2024-08-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_contrato_data_primeiro_vencimento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato',
            old_name='data_primeiro_vencimento',
            new_name='data_primeiro_vencimento_pagar',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='periodicidade',
        ),
        migrations.AddField(
            model_name='contrato',
            name='data_primeiro_vencimento_receber',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='periodicidade_vencimento_pagar',
            field=models.CharField(blank=True, choices=[('mensal', 'Mensal'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='periodicidade_vencimento_receber',
            field=models.CharField(blank=True, choices=[('mensal', 'Mensal'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='valor_parcela_pagar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='valor_parcela_receber',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
