# Generated by Django 5.0.7 on 2024-08-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0003_rename_data_primeiro_vencimento_contrato_data_primeiro_vencimento_pagar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
