# Generated by Django 5.0.7 on 2024-09-12 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0004_contrato_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjecaoFaturamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vencimento', models.DateField()),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pago', models.BooleanField(blank=True, default=False, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projecoes_faturamento', to='contratos.contrato')),
            ],
        ),
    ]
