# Generated by Django 5.1.6 on 2025-02-14 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0005_projecaofaturamento'),
        ('projetos', '0002_projeto_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato',
            old_name='data_primeiro_vencimento_pagar',
            new_name='data_primeiro_vencimento',
        ),
        migrations.RenameField(
            model_name='contrato',
            old_name='periodicidade_vencimento_pagar',
            new_name='periodicidade_vencimento',
        ),
        migrations.RenameField(
            model_name='contrato',
            old_name='valor_parcela_pagar',
            new_name='valor_parcela',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='data_primeiro_vencimento_receber',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='periodicidade_vencimento_receber',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='valor_parcela_receber',
        ),
        migrations.AddField(
            model_name='contrato',
            name='confirmado',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ContratoProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_projeto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrato_projetos', to='contratos.contrato')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrato_projetos', to='projetos.projeto')),
            ],
            options={
                'unique_together': {('contrato', 'projeto')},
            },
        ),
    ]
