# Generated by Django 5.1.1 on 2025-06-13 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('funcionarios', '0002_remove_funcionario_filial_funcionario_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='empresa',
            field=models.ForeignKey(
                'empresas.Empresa',     # referência por string
                on_delete=models.PROTECT,
                db_constraint=False,
                db_index=True,
                null=True,
                blank=True
            ),
        ),
    ]
