<<<<<<< HEAD
# Generated by Django 5.1.2 on 2024-10-15 17:59

import django.core.validators
=======
# Generated by Django 5.1.1 on 2025-05-29 18:22

import django.core.validators
import django.db.models.deletion
>>>>>>> e62255e (Atualizações no projeto)
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        ('empresas', '0001_initial'),
>>>>>>> e62255e (Atualizações no projeto)
    ]

    operations = [
        migrations.CreateModel(
            name='CentroCusto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=100)),
                ('mascara_centro_custo', models.CharField(max_length=3, unique=True)),
<<<<<<< HEAD
=======
                ('is_active', models.BooleanField(default=True)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresas.filial')),
>>>>>>> e62255e (Atualizações no projeto)
            ],
        ),
        migrations.CreateModel(
            name='ContaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mascara_conta', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='A máscara deve seguir o formato 1.11.111.1111', regex='^\\d\\.\\d{2}\\.\\d{3}\\.\\d{4}$')])),
                ('descricao', models.CharField(max_length=100)),
<<<<<<< HEAD
=======
                ('is_active', models.BooleanField(default=True)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresas.filial')),
>>>>>>> e62255e (Atualizações no projeto)
            ],
        ),
    ]
