# Generated by Django 5.1.2 on 2024-10-15 17:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentroCusto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=100)),
                ('mascara_centro_custo', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mascara_conta', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='A máscara deve seguir o formato 1.11.111.1111', regex='^\\d\\.\\d{2}\\.\\d{3}\\.\\d{4}$')])),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
    ]
