# Generated by Django 5.1.2 on 2024-10-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='centrocusto',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contafinanceira',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
