# Generated by Django 5.1.1 on 2025-06-01 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('financeiro', '0002_remove_centrocusto_filial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centrocusto',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresas.empresa'),
        ),
        migrations.AlterField(
            model_name='contafinanceira',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresas.empresa'),
        ),
    ]
