# Generated by Django 5.1.1 on 2025-06-10 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('financeiro', '0003_alter_centrocusto_empresa_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centrocusto',
            options={'verbose_name': 'Centro de Custo', 'verbose_name_plural': 'Centros de Custo'},
        ),
        migrations.AlterModelOptions(
            name='contafinanceira',
            options={'verbose_name': 'Conta Financeira', 'verbose_name_plural': 'Contas Financeiras'},
        ),
        migrations.AlterField(
            model_name='centrocusto',
            name='mascara_centro_custo',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='contafinanceira',
            name='mascara_conta',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message='A máscara deve seguir o formato 1.11.111.1111', regex='^\\d\\.\\d{2}\\.\\d{3}\\.\\d{4}$')]),
        ),
        migrations.AlterUniqueTogether(
            name='centrocusto',
            unique_together={('empresa', 'mascara_centro_custo')},
        ),
        migrations.AlterUniqueTogether(
            name='contafinanceira',
            unique_together={('empresa', 'mascara_conta')},
        ),
    ]
