# Generated by Django 5.1.1 on 2025-06-10 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('financeiro', '0004_alter_centrocusto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contafinanceira',
            name='empresa',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, to='empresas.empresa'),
        ),
    ]
