# Generated by Django 5.1.1 on 2025-06-20 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('financeiro', '0005_alter_contafinanceira_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centrocusto',
            name='empresa',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, to='empresas.empresa'),
        ),
    ]
