<<<<<<< HEAD
# Generated by Django 4.2.14 on 2024-07-31 00:48

=======
# Generated by Django 5.1.1 on 2025-05-29 18:22

import django.db.models.deletion
>>>>>>> e62255e (Atualizações no projeto)
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        ('empresas', '0001_initial'),
>>>>>>> e62255e (Atualizações no projeto)
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateField()),
<<<<<<< HEAD
                ('data_termino', models.DateField()),
                ('status', models.CharField(choices=[('andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='andamento', max_length=10)),
=======
                ('data_termino', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='andamento', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='empresas.filial')),
>>>>>>> e62255e (Atualizações no projeto)
            ],
        ),
    ]
