# Generated by Django 5.0.7 on 2024-09-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
