# Generated by Django 5.1.1 on 2025-06-13 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('projetos', '0003_alter_projeto_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='empresa',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa'),
        ),
    ]
