# Generated by Django 4.2.14 on 2024-08-04 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
        ('pagamentos', '0001_initial'),
        ('contratos', '0001_initial'),
        ('contas_pagar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaAPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField()),
                ('competencia', models.DateField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contratos.contrato')),
                ('forma_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pagamentos.formapagamento')),
            ],
        ),
        migrations.CreateModel(
            name='ProjetoContaAPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('conta_a_pagar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='contas_pagar.contaapagar')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projetos.projeto')),
            ],
        ),
        migrations.RemoveField(
            model_name='projetocontapagar',
            name='conta_pagar',
        ),
        migrations.RemoveField(
            model_name='projetocontapagar',
            name='projeto',
        ),
        migrations.DeleteModel(
            name='ContaPagar',
        ),
        migrations.DeleteModel(
            name='Contrato',
        ),
        migrations.DeleteModel(
            name='FormaPagamento',
        ),
        migrations.DeleteModel(
            name='Projeto',
        ),
        migrations.DeleteModel(
            name='ProjetoContaPagar',
        ),
    ]
