# Generated by Django 5.1.1 on 2025-06-02 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas_pagar', '0002_remove_contaapagar_filial_and_more'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contaapagar',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresas.empresa'),
        ),
        migrations.AlterField(
            model_name='contaareceber',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresas.empresa'),
        ),
        migrations.AlterField(
            model_name='contapagaravulso',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresas.empresa'),
        ),
        migrations.AlterField(
            model_name='contareceberavulso',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresas.empresa'),
        ),
    ]
