# Generated by Django 4.2.14 on 2024-08-05 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
        ('pagamentos', '0001_initial'),
        ('projetos', '0001_initial'),
        ('contas_pagar', '0002_contaapagar_projetocontaapagar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaAReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_recebimento', models.DateField()),
                ('competencia', models.DateField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contrato', models.ForeignKey(limit_choices_to={'tipo': 'cliente'}, on_delete=django.db.models.deletion.PROTECT, to='contratos.contrato')),
                ('forma_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pagamentos.formapagamento')),
            ],
        ),
        migrations.CreateModel(
            name='ProjetoContaAReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('conta_a_receber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='contas_pagar.contaareceber')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projetos.projeto')),
            ],
        ),
    ]
