# Generated by Django 5.0.7 on 2024-08-06 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas_pagar', '0003_contaareceber_projetocontaareceber'),
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contaapagar',
            name='projetos',
            field=models.ManyToManyField(to='projetos.projeto'),
        ),
        migrations.AlterField(
            model_name='projetocontaapagar',
            name='conta_a_pagar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projeto_contas_a_pagar', to='contas_pagar.contaapagar'),
        ),
    ]
