# Generated by Django 5.0.7 on 2024-08-09 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('contas_pagar', '0004_contaapagar_projetos_and_more'),
        ('fornecedores', '0001_initial'),
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaPagarAvulso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_pagamento', models.DateField()),
                ('competencia', models.CharField(max_length=7)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fornecedores.fornecedor')),
                ('projetos', models.ManyToManyField(blank=True, to='projetos.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='ContaReceberAvulso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_recebimento', models.DateField()),
                ('competencia', models.CharField(max_length=7)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
                ('projetos', models.ManyToManyField(blank=True, to='projetos.projeto')),
            ],
        ),
    ]
