# Generated by Django 5.1.1 on 2025-07-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas_pagar', '0005_alter_contapagaravulso_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contareceberavulso',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('recebido', 'Recebido'), ('estornado', 'Estornado')], default='pendente', max_length=20),
        ),
    ]
