# Generated by Django 5.1.2 on 2024-10-21 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas_pagar', '0005_contapagaravulso_contareceberavulso'),
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contaareceber',
            name='centro_custo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.centrocusto'),
        ),
        migrations.AddField(
            model_name='contaareceber',
            name='conta_financeira',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.contafinanceira'),
        ),
    ]
