# Generated by Django 5.1.2 on 2024-10-22 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas_pagar', '0006_contaareceber_centro_custo_and_more'),
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contaapagar',
            name='centro_custo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.centrocusto'),
        ),
        migrations.AddField(
            model_name='contaapagar',
            name='conta_financeira',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.contafinanceira'),
        ),
        migrations.AddField(
            model_name='contapagaravulso',
            name='centro_custo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.centrocusto'),
        ),
        migrations.AddField(
            model_name='contapagaravulso',
            name='conta_financeira',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.contafinanceira'),
        ),
        migrations.AddField(
            model_name='contareceberavulso',
            name='centro_custo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.centrocusto'),
        ),
        migrations.AddField(
            model_name='contareceberavulso',
            name='conta_financeira',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.contafinanceira'),
        ),
    ]
