# Generated by Django 5.1.2 on 2024-10-31 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas_pagar', '0007_contaapagar_centro_custo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contaapagar',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contaareceber',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contapagaravulso',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contareceberavulso',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
