# Generated by Django 5.1.6 on 2025-02-18 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas_pagar', '0008_contaapagar_is_active_contaareceber_is_active_and_more'),
        ('contratos', '0006_rename_data_primeiro_vencimento_pagar_contrato_data_primeiro_vencimento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projetocontaareceber',
            name='conta_a_receber',
        ),
        migrations.RemoveField(
            model_name='projetocontaareceber',
            name='projeto',
        ),
        migrations.RemoveField(
            model_name='contaapagar',
            name='projetos',
        ),
        migrations.AlterField(
            model_name='contaapagar',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_pagar', to='contratos.contrato'),
        ),
        migrations.AlterField(
            model_name='contaareceber',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_receber', to='contratos.contrato'),
        ),
        migrations.DeleteModel(
            name='ProjetoContaAPagar',
        ),
        migrations.DeleteModel(
            name='ProjetoContaAReceber',
        ),
    ]
