# Generated by Django 5.1.6 on 2025-02-19 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas_pagar', '0009_remove_projetocontaareceber_conta_a_receber_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contaareceber',
            options={'ordering': ['-data_recebimento']},
        ),
    ]
