# Generated by Django 5.1.6 on 2025-02-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas_pagar', '0010_alter_contaareceber_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contaapagar',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('estornado', 'Estornado')], default='pendente', max_length=20),
        ),
        migrations.AddField(
            model_name='contaareceber',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('recebido', 'Recebido'), ('estornado', 'Estornado')], default='pendente', max_length=20),
        ),
    ]
