<<<<<<< HEAD
# Generated by Django 4.2.14 on 2024-07-31 01:15

=======
# Generated by Django 5.1.1 on 2025-05-29 18:22

import django.db.models.deletion
>>>>>>> e62255e (Atualizações no projeto)
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        ('empresas', '0001_initial'),
>>>>>>> e62255e (Atualizações no projeto)
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito'), ('boleto', 'Boleto'), ('pix', 'PIX')], max_length=20)),
<<<<<<< HEAD
=======
                ('is_active', models.BooleanField(default=True)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresas.filial')),
>>>>>>> e62255e (Atualizações no projeto)
            ],
        ),
    ]
