# Generated by Django 5.1.1 on 2025-06-03 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('pagamentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formapagamento',
            name='filial',
        ),
        migrations.AddField(
            model_name='formapagamento',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='formas_pagamento', to='empresas.empresa'),
        ),
    ]
