# Generated by Django 5.1.1 on 2025-06-03 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('pagamentos', '0002_remove_formapagamento_filial_formapagamento_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formapagamento',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formas_pagamento', to='empresas.empresa'),
        ),
    ]
