# Generated by Django 5.1.1 on 2025-06-13 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('pagamentos', '0003_alter_formapagamento_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formapagamento',
            name='empresa',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, to='empresas.empresa'),
        ),
    ]
