# Generated by Django 5.1.2 on 2024-11-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0002_fornecedor_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
